name: build

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: alextes
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract short SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ultrasoundorg/ultrasoundmoney-frontend:${{ env.SHORT_SHA }}
            ultrasoundorg/ultrasoundmoney-frontend:latest
          cache-from: type=local,src=/tmp/.buildx-cache-${{ github.event.repository.name }}
          cache-to: type=local,dest=/tmp/.buildx-cache-new-${{ github.event.repository.name }},mode=max
          secrets: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
            "NEXT_PUBLIC_TAGS=${{ github.ref_name }}"
            "NEXT_PUBLIC_COMMIT=${{ github.sha }}"

      # build cache doesn't expire, so we rewrite the cache every time
      # and drop the old one. see:
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-${{ github.event.repository.name }}
          mv /tmp/.buildx-cache-new-${{ github.event.repository.name }} /tmp/.buildx-cache-${{ github.event.repository.name }}
