name: test

on:
  push:
    tags:
      - "stag-*"
  pull_request:
    branches: [main]

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: install deps
        run: yarn install
      - name: test
        run: yarn build
